/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.webmanifest]'
import { Route as DesignRouteImport } from './routes/design'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommonRouteImport } from './routes/_common'
import { Route as ModeratorRouteImport } from './routes/$moderator'
import { Route as DesignIndexRouteImport } from './routes/design.index'
import { Route as CommonIndexRouteImport } from './routes/_common.index'
import { Route as ModeratorIndexRouteImport } from './routes/$moderator.index'
import { Route as OgSplatRouteImport } from './routes/og.$'
import { Route as AuthVerifyMailRouteImport } from './routes/auth.verify-mail'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiParsingRouteImport } from './routes/api/parsing'
import { Route as ApiExperimentRouteImport } from './routes/api/experiment'
import { Route as ApiImageRouteImport } from './routes/api/_image'
import { Route as CommonWhisperRoomRouteImport } from './routes/_common.whisper-room'
import { Route as CommonTermsRouteImport } from './routes/_common.terms'
import { Route as CommonPrivacyPolicyRouteImport } from './routes/_common.privacy-policy'
import { Route as CommonContactRouteImport } from './routes/_common.contact'
import { Route as CommonCommunityRouteImport } from './routes/_common.community'
import { Route as CommonClassroomAvailabilityRouteImport } from './routes/_common.classroom-availability'
import { Route as CommonChatRouteImport } from './routes/_common.chat'
import { Route as CommonBenefitsRouteImport } from './routes/_common.benefits'
import { Route as CommonAcademicCalendarRouteImport } from './routes/_common.academic-calendar'
import { Route as CommonAboutRouteImport } from './routes/_common.about'
import { Route as ModeratorTestingRouteImport } from './routes/$moderator.testing'
import { Route as ModeratorTestRouteImport } from './routes/$moderator.test'
import { Route as ModeratorSettingsRouteImport } from './routes/$moderator.settings'
import { Route as ModeratorOutpassRouteImport } from './routes/$moderator.outpass'
import { Route as ModeratorHostelsRouteImport } from './routes/$moderator.hostels'
import { Route as ModeratorHostelRoomAllotmentRouteImport } from './routes/$moderator.hostel-room-allotment'
import { Route as ModeratorClassroomRouteImport } from './routes/$moderator.classroom'
import { Route as ModeratorClassesRouteImport } from './routes/$moderator.classes'
import { Route as ProgramsBuilderClubIndexRouteImport } from './routes/programs.builder-club.index'
import { Route as CommonWhisperRoomIndexRouteImport } from './routes/_common.whisper-room.index'
import { Route as CommonSyllabusIndexRouteImport } from './routes/_common.syllabus.index'
import { Route as CommonSchedulesIndexRouteImport } from './routes/_common.schedules.index'
import { Route as CommonResultsIndexRouteImport } from './routes/_common.results.index'
import { Route as CommonResourcesIndexRouteImport } from './routes/_common.resources.index'
import { Route as CommonPollsIndexRouteImport } from './routes/_common.polls.index'
import { Route as CommonCommunityIndexRouteImport } from './routes/_common.community.index'
import { Route as CommonAnnouncementsIndexRouteImport } from './routes/_common.announcements.index'
import { Route as ModeratorUsersIndexRouteImport } from './routes/$moderator.users.index'
import { Route as ModeratorSettingsIndexRouteImport } from './routes/$moderator.settings.index'
import { Route as ModeratorSchedulesIndexRouteImport } from './routes/$moderator.schedules.index'
import { Route as ModeratorRoomsIndexRouteImport } from './routes/$moderator.rooms.index'
import { Route as ModeratorResultIndexRouteImport } from './routes/$moderator.result.index'
import { Route as ModeratorOutpassIndexRouteImport } from './routes/$moderator.outpass.index'
import { Route as ModeratorHostelsIndexRouteImport } from './routes/$moderator.hostels.index'
import { Route as ModeratorEventsIndexRouteImport } from './routes/$moderator.events.index'
import { Route as ModeratorCoursesIndexRouteImport } from './routes/$moderator.courses.index'
import { Route as ModeratorAttendancePersonalIndexRouteImport } from './routes/$moderator.attendance-personal.index'
import { Route as ProgramsBuilderClubApplyNowRouteImport } from './routes/programs.builder-club.apply-now'
import { Route as ApiOutpassStatusRouteImport } from './routes/api/outpass.status'
import { Route as ApiOutpassListRouteImport } from './routes/api/outpass.list'
import { Route as ApiHostelRoomMembersRouteImport } from './routes/api/hostel.room-members'
import { Route as ApiHostelAllotmentSlotRouteImport } from './routes/api/hostel.allotment-slot'
import { Route as ApiCommentsSplatRouteImport } from './routes/api/comments.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as CommonWhisperRoomWhisperRouteImport } from './routes/_common.whisper-room.whisper'
import { Route as CommonUUsernameRouteImport } from './routes/_common.u.$username'
import { Route as CommonSyllabusCodeRouteImport } from './routes/_common.syllabus.$code'
import { Route as CommonSchedulesSplatRouteImport } from './routes/_common.schedules.$'
import { Route as CommonResultsRollNoRouteImport } from './routes/_common.results.$rollNo'
import { Route as CommonPollsPollIdRouteImport } from './routes/_common.polls.$pollId'
import { Route as CommonCommunityEditRouteImport } from './routes/_common.community.edit'
import { Route as CommonCommunityCreateRouteImport } from './routes/_common.community.create'
import { Route as CommonAnnouncementsCreateRouteImport } from './routes/_common.announcements.create'
import { Route as ModeratorUsersNewRouteImport } from './routes/$moderator.users.new'
import { Route as ModeratorUsersIdRouteImport } from './routes/$moderator.users.$id'
import { Route as ModeratorSettingsAppearanceRouteImport } from './routes/$moderator.settings.appearance'
import { Route as ModeratorSettingsAccountRouteImport } from './routes/$moderator.settings.account'
import { Route as ModeratorSchedulesCreateRouteImport } from './routes/$moderator.schedules.create'
import { Route as ModeratorSchedulesSplatRouteImport } from './routes/$moderator.schedules.$'
import { Route as ModeratorRoomsNewRouteImport } from './routes/$moderator.rooms.new'
import { Route as ModeratorResultScrapingRouteImport } from './routes/$moderator.result.scraping'
import { Route as ModeratorResultImportRouteImport } from './routes/$moderator.result.import'
import { Route as ModeratorOutpassRequestRouteImport } from './routes/$moderator.outpass.request'
import { Route as ModeratorOutpassIdRouteImport } from './routes/$moderator.outpass.$id'
import { Route as ModeratorHostelsSlugRouteImport } from './routes/$moderator.hostels.$slug'
import { Route as ModeratorHSlugRouteImport } from './routes/$moderator.h.$slug'
import { Route as ModeratorEventsNewRouteImport } from './routes/$moderator.events.new'
import { Route as ModeratorCoursesCreateRouteImport } from './routes/$moderator.courses.create'
import { Route as ModeratorCoursesCourseCodeRouteImport } from './routes/$moderator.courses.$courseCode'
import { Route as ModeratorAttendancePersonalIdRouteImport } from './routes/$moderator.attendance-personal.$id'
import { Route as CommonWhisperRoomFeedIndexRouteImport } from './routes/_common.whisper-room.feed.index'
import { Route as CommonResourcesTypeIndexRouteImport } from './routes/_common.resources.$type.index'
import { Route as ModeratorHSlugIndexRouteImport } from './routes/$moderator.h.$slug.index'
import { Route as ModeratorEventsIdIndexRouteImport } from './routes/$moderator.events.$id.index'
import { Route as CommonResourcesStoriesShareRouteImport } from './routes/_common.resources.stories.share'
import { Route as CommonResourcesStoriesIdRouteImport } from './routes/_common.resources.stories.$id'
import { Route as CommonResourcesTypeSlugRouteImport } from './routes/_common.resources.$type.$slug'
import { Route as CommonCommunityPostsPostIdRouteImport } from './routes/_common.community.posts.$postId'
import { Route as ModeratorHSlugStudentsRouteImport } from './routes/$moderator.h.$slug.students'
import { Route as ModeratorHSlugRoomsRouteImport } from './routes/$moderator.h.$slug.rooms'
import { Route as ModeratorHSlugOutpassRequestsRouteImport } from './routes/$moderator.h.$slug.outpass-requests'
import { Route as ModeratorHSlugAllotmentByExcelRouteImport } from './routes/$moderator.h.$slug.allotment-by-excel'
import { Route as ModeratorHSlugAllotmentRouteImport } from './routes/$moderator.h.$slug.allotment'
import { Route as ModeratorEventsIdEditRouteImport } from './routes/$moderator.events.$id.edit'
import { Route as CommonWhisperRoomFeedPostIdIndexRouteImport } from './routes/_common.whisper-room.feed.$postId.index'
import { Route as ModeratorHSlugOutpassLogsIndexRouteImport } from './routes/$moderator.h.$slug.outpass-logs.index'
import { Route as CommonWhisperRoomFeedPostIdEditRouteImport } from './routes/_common.whisper-room.feed.$postId.edit'
import { Route as ModeratorHSlugOutpassLogsStudentIdRouteImport } from './routes/$moderator.h.$slug.outpass-logs.$studentId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonRoute = CommonRouteImport.update({
  id: '/_common',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeratorRoute = ModeratorRouteImport.update({
  id: '/$moderator',
  path: '/$moderator',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignIndexRoute = DesignIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DesignRoute,
} as any)
const CommonIndexRoute = CommonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommonRoute,
} as any)
const ModeratorIndexRoute = ModeratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorRoute,
} as any)
const OgSplatRoute = OgSplatRouteImport.update({
  id: '/og/$',
  path: '/og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyMailRoute = AuthVerifyMailRouteImport.update({
  id: '/verify-mail',
  path: '/verify-mail',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParsingRoute = ApiParsingRouteImport.update({
  id: '/api/parsing',
  path: '/api/parsing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExperimentRoute = ApiExperimentRouteImport.update({
  id: '/api/experiment',
  path: '/api/experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/_image',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonWhisperRoomRoute = CommonWhisperRoomRouteImport.update({
  id: '/whisper-room',
  path: '/whisper-room',
  getParentRoute: () => CommonRoute,
} as any)
const CommonTermsRoute = CommonTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => CommonRoute,
} as any)
const CommonPrivacyPolicyRoute = CommonPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => CommonRoute,
} as any)
const CommonContactRoute = CommonContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CommonRoute,
} as any)
const CommonCommunityRoute = CommonCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => CommonRoute,
} as any)
const CommonClassroomAvailabilityRoute =
  CommonClassroomAvailabilityRouteImport.update({
    id: '/classroom-availability',
    path: '/classroom-availability',
    getParentRoute: () => CommonRoute,
  } as any)
const CommonChatRoute = CommonChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CommonRoute,
} as any)
const CommonBenefitsRoute = CommonBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => CommonRoute,
} as any)
const CommonAcademicCalendarRoute = CommonAcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => CommonRoute,
} as any)
const CommonAboutRoute = CommonAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => CommonRoute,
} as any)
const ModeratorTestingRoute = ModeratorTestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorTestRoute = ModeratorTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorSettingsRoute = ModeratorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorOutpassRoute = ModeratorOutpassRouteImport.update({
  id: '/outpass',
  path: '/outpass',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorHostelsRoute = ModeratorHostelsRouteImport.update({
  id: '/hostels',
  path: '/hostels',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorHostelRoomAllotmentRoute =
  ModeratorHostelRoomAllotmentRouteImport.update({
    id: '/hostel-room-allotment',
    path: '/hostel-room-allotment',
    getParentRoute: () => ModeratorRoute,
  } as any)
const ModeratorClassroomRoute = ModeratorClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorClassesRoute = ModeratorClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => ModeratorRoute,
} as any)
const ProgramsBuilderClubIndexRoute =
  ProgramsBuilderClubIndexRouteImport.update({
    id: '/builder-club/',
    path: '/builder-club/',
    getParentRoute: () => ProgramsRoute,
  } as any)
const CommonWhisperRoomIndexRoute = CommonWhisperRoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommonWhisperRoomRoute,
} as any)
const CommonSyllabusIndexRoute = CommonSyllabusIndexRouteImport.update({
  id: '/syllabus/',
  path: '/syllabus/',
  getParentRoute: () => CommonRoute,
} as any)
const CommonSchedulesIndexRoute = CommonSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => CommonRoute,
} as any)
const CommonResultsIndexRoute = CommonResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => CommonRoute,
} as any)
const CommonResourcesIndexRoute = CommonResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => CommonRoute,
} as any)
const CommonPollsIndexRoute = CommonPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => CommonRoute,
} as any)
const CommonCommunityIndexRoute = CommonCommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommonCommunityRoute,
} as any)
const CommonAnnouncementsIndexRoute =
  CommonAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => CommonRoute,
  } as any)
const ModeratorUsersIndexRoute = ModeratorUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorSettingsIndexRoute = ModeratorSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorSettingsRoute,
} as any)
const ModeratorSchedulesIndexRoute = ModeratorSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorRoomsIndexRoute = ModeratorRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorResultIndexRoute = ModeratorResultIndexRouteImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorOutpassIndexRoute = ModeratorOutpassIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorOutpassRoute,
} as any)
const ModeratorHostelsIndexRoute = ModeratorHostelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorHostelsRoute,
} as any)
const ModeratorEventsIndexRoute = ModeratorEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorCoursesIndexRoute = ModeratorCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorAttendancePersonalIndexRoute =
  ModeratorAttendancePersonalIndexRouteImport.update({
    id: '/attendance-personal/',
    path: '/attendance-personal/',
    getParentRoute: () => ModeratorRoute,
  } as any)
const ProgramsBuilderClubApplyNowRoute =
  ProgramsBuilderClubApplyNowRouteImport.update({
    id: '/builder-club/apply-now',
    path: '/builder-club/apply-now',
    getParentRoute: () => ProgramsRoute,
  } as any)
const ApiOutpassStatusRoute = ApiOutpassStatusRouteImport.update({
  id: '/api/outpass/status',
  path: '/api/outpass/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOutpassListRoute = ApiOutpassListRouteImport.update({
  id: '/api/outpass/list',
  path: '/api/outpass/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostelRoomMembersRoute = ApiHostelRoomMembersRouteImport.update({
  id: '/api/hostel/room-members',
  path: '/api/hostel/room-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHostelAllotmentSlotRoute = ApiHostelAllotmentSlotRouteImport.update({
  id: '/api/hostel/allotment-slot',
  path: '/api/hostel/allotment-slot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsSplatRoute = ApiCommentsSplatRouteImport.update({
  id: '/api/comments/$',
  path: '/api/comments/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonWhisperRoomWhisperRoute =
  CommonWhisperRoomWhisperRouteImport.update({
    id: '/whisper',
    path: '/whisper',
    getParentRoute: () => CommonWhisperRoomRoute,
  } as any)
const CommonUUsernameRoute = CommonUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => CommonRoute,
} as any)
const CommonSyllabusCodeRoute = CommonSyllabusCodeRouteImport.update({
  id: '/syllabus/$code',
  path: '/syllabus/$code',
  getParentRoute: () => CommonRoute,
} as any)
const CommonSchedulesSplatRoute = CommonSchedulesSplatRouteImport.update({
  id: '/schedules/$',
  path: '/schedules/$',
  getParentRoute: () => CommonRoute,
} as any)
const CommonResultsRollNoRoute = CommonResultsRollNoRouteImport.update({
  id: '/results/$rollNo',
  path: '/results/$rollNo',
  getParentRoute: () => CommonRoute,
} as any)
const CommonPollsPollIdRoute = CommonPollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => CommonRoute,
} as any)
const CommonCommunityEditRoute = CommonCommunityEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CommonCommunityRoute,
} as any)
const CommonCommunityCreateRoute = CommonCommunityCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CommonCommunityRoute,
} as any)
const CommonAnnouncementsCreateRoute =
  CommonAnnouncementsCreateRouteImport.update({
    id: '/announcements/create',
    path: '/announcements/create',
    getParentRoute: () => CommonRoute,
  } as any)
const ModeratorUsersNewRoute = ModeratorUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorUsersIdRoute = ModeratorUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorSettingsAppearanceRoute =
  ModeratorSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ModeratorSettingsRoute,
  } as any)
const ModeratorSettingsAccountRoute =
  ModeratorSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => ModeratorSettingsRoute,
  } as any)
const ModeratorSchedulesCreateRoute =
  ModeratorSchedulesCreateRouteImport.update({
    id: '/schedules/create',
    path: '/schedules/create',
    getParentRoute: () => ModeratorRoute,
  } as any)
const ModeratorSchedulesSplatRoute = ModeratorSchedulesSplatRouteImport.update({
  id: '/schedules/$',
  path: '/schedules/$',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorRoomsNewRoute = ModeratorRoomsNewRouteImport.update({
  id: '/rooms/new',
  path: '/rooms/new',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorResultScrapingRoute = ModeratorResultScrapingRouteImport.update({
  id: '/result/scraping',
  path: '/result/scraping',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorResultImportRoute = ModeratorResultImportRouteImport.update({
  id: '/result/import',
  path: '/result/import',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorOutpassRequestRoute = ModeratorOutpassRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => ModeratorOutpassRoute,
} as any)
const ModeratorOutpassIdRoute = ModeratorOutpassIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ModeratorOutpassRoute,
} as any)
const ModeratorHostelsSlugRoute = ModeratorHostelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModeratorHostelsRoute,
} as any)
const ModeratorHSlugRoute = ModeratorHSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorEventsNewRoute = ModeratorEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorCoursesCreateRoute = ModeratorCoursesCreateRouteImport.update({
  id: '/courses/create',
  path: '/courses/create',
  getParentRoute: () => ModeratorRoute,
} as any)
const ModeratorCoursesCourseCodeRoute =
  ModeratorCoursesCourseCodeRouteImport.update({
    id: '/courses/$courseCode',
    path: '/courses/$courseCode',
    getParentRoute: () => ModeratorRoute,
  } as any)
const ModeratorAttendancePersonalIdRoute =
  ModeratorAttendancePersonalIdRouteImport.update({
    id: '/attendance-personal/$id',
    path: '/attendance-personal/$id',
    getParentRoute: () => ModeratorRoute,
  } as any)
const CommonWhisperRoomFeedIndexRoute =
  CommonWhisperRoomFeedIndexRouteImport.update({
    id: '/feed/',
    path: '/feed/',
    getParentRoute: () => CommonWhisperRoomRoute,
  } as any)
const CommonResourcesTypeIndexRoute =
  CommonResourcesTypeIndexRouteImport.update({
    id: '/resources/$type/',
    path: '/resources/$type/',
    getParentRoute: () => CommonRoute,
  } as any)
const ModeratorHSlugIndexRoute = ModeratorHSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModeratorHSlugRoute,
} as any)
const ModeratorEventsIdIndexRoute = ModeratorEventsIdIndexRouteImport.update({
  id: '/events/$id/',
  path: '/events/$id/',
  getParentRoute: () => ModeratorRoute,
} as any)
const CommonResourcesStoriesShareRoute =
  CommonResourcesStoriesShareRouteImport.update({
    id: '/resources/stories/share',
    path: '/resources/stories/share',
    getParentRoute: () => CommonRoute,
  } as any)
const CommonResourcesStoriesIdRoute =
  CommonResourcesStoriesIdRouteImport.update({
    id: '/resources/stories/$id',
    path: '/resources/stories/$id',
    getParentRoute: () => CommonRoute,
  } as any)
const CommonResourcesTypeSlugRoute = CommonResourcesTypeSlugRouteImport.update({
  id: '/resources/$type/$slug',
  path: '/resources/$type/$slug',
  getParentRoute: () => CommonRoute,
} as any)
const CommonCommunityPostsPostIdRoute =
  CommonCommunityPostsPostIdRouteImport.update({
    id: '/posts/$postId',
    path: '/posts/$postId',
    getParentRoute: () => CommonCommunityRoute,
  } as any)
const ModeratorHSlugStudentsRoute = ModeratorHSlugStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => ModeratorHSlugRoute,
} as any)
const ModeratorHSlugRoomsRoute = ModeratorHSlugRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => ModeratorHSlugRoute,
} as any)
const ModeratorHSlugOutpassRequestsRoute =
  ModeratorHSlugOutpassRequestsRouteImport.update({
    id: '/outpass-requests',
    path: '/outpass-requests',
    getParentRoute: () => ModeratorHSlugRoute,
  } as any)
const ModeratorHSlugAllotmentByExcelRoute =
  ModeratorHSlugAllotmentByExcelRouteImport.update({
    id: '/allotment-by-excel',
    path: '/allotment-by-excel',
    getParentRoute: () => ModeratorHSlugRoute,
  } as any)
const ModeratorHSlugAllotmentRoute = ModeratorHSlugAllotmentRouteImport.update({
  id: '/allotment',
  path: '/allotment',
  getParentRoute: () => ModeratorHSlugRoute,
} as any)
const ModeratorEventsIdEditRoute = ModeratorEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => ModeratorRoute,
} as any)
const CommonWhisperRoomFeedPostIdIndexRoute =
  CommonWhisperRoomFeedPostIdIndexRouteImport.update({
    id: '/feed/$postId/',
    path: '/feed/$postId/',
    getParentRoute: () => CommonWhisperRoomRoute,
  } as any)
const ModeratorHSlugOutpassLogsIndexRoute =
  ModeratorHSlugOutpassLogsIndexRouteImport.update({
    id: '/outpass-logs/',
    path: '/outpass-logs/',
    getParentRoute: () => ModeratorHSlugRoute,
  } as any)
const CommonWhisperRoomFeedPostIdEditRoute =
  CommonWhisperRoomFeedPostIdEditRouteImport.update({
    id: '/feed/$postId/edit',
    path: '/feed/$postId/edit',
    getParentRoute: () => CommonWhisperRoomRoute,
  } as any)
const ModeratorHSlugOutpassLogsStudentIdRoute =
  ModeratorHSlugOutpassLogsStudentIdRouteImport.update({
    id: '/outpass-logs/$studentId',
    path: '/outpass-logs/$studentId',
    getParentRoute: () => ModeratorHSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$moderator': typeof ModeratorRouteWithChildren
  '/': typeof CommonIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/$moderator/classes': typeof ModeratorClassesRoute
  '/$moderator/classroom': typeof ModeratorClassroomRoute
  '/$moderator/hostel-room-allotment': typeof ModeratorHostelRoomAllotmentRoute
  '/$moderator/hostels': typeof ModeratorHostelsRouteWithChildren
  '/$moderator/outpass': typeof ModeratorOutpassRouteWithChildren
  '/$moderator/settings': typeof ModeratorSettingsRouteWithChildren
  '/$moderator/test': typeof ModeratorTestRoute
  '/$moderator/testing': typeof ModeratorTestingRoute
  '/about': typeof CommonAboutRoute
  '/academic-calendar': typeof CommonAcademicCalendarRoute
  '/benefits': typeof CommonBenefitsRoute
  '/chat': typeof CommonChatRoute
  '/classroom-availability': typeof CommonClassroomAvailabilityRoute
  '/community': typeof CommonCommunityRouteWithChildren
  '/contact': typeof CommonContactRoute
  '/privacy-policy': typeof CommonPrivacyPolicyRoute
  '/terms': typeof CommonTermsRoute
  '/whisper-room': typeof CommonWhisperRoomRouteWithChildren
  '/api': typeof ApiImageRoute
  '/api/experiment': typeof ApiExperimentRoute
  '/api/parsing': typeof ApiParsingRoute
  '/api/stats': typeof ApiStatsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify-mail': typeof AuthVerifyMailRoute
  '/og/$': typeof OgSplatRoute
  '/$moderator/': typeof ModeratorIndexRoute
  '/design/': typeof DesignIndexRoute
  '/$moderator/attendance-personal/$id': typeof ModeratorAttendancePersonalIdRoute
  '/$moderator/courses/$courseCode': typeof ModeratorCoursesCourseCodeRoute
  '/$moderator/courses/create': typeof ModeratorCoursesCreateRoute
  '/$moderator/events/new': typeof ModeratorEventsNewRoute
  '/$moderator/h/$slug': typeof ModeratorHSlugRouteWithChildren
  '/$moderator/hostels/$slug': typeof ModeratorHostelsSlugRoute
  '/$moderator/outpass/$id': typeof ModeratorOutpassIdRoute
  '/$moderator/outpass/request': typeof ModeratorOutpassRequestRoute
  '/$moderator/result/import': typeof ModeratorResultImportRoute
  '/$moderator/result/scraping': typeof ModeratorResultScrapingRoute
  '/$moderator/rooms/new': typeof ModeratorRoomsNewRoute
  '/$moderator/schedules/$': typeof ModeratorSchedulesSplatRoute
  '/$moderator/schedules/create': typeof ModeratorSchedulesCreateRoute
  '/$moderator/settings/account': typeof ModeratorSettingsAccountRoute
  '/$moderator/settings/appearance': typeof ModeratorSettingsAppearanceRoute
  '/$moderator/users/$id': typeof ModeratorUsersIdRoute
  '/$moderator/users/new': typeof ModeratorUsersNewRoute
  '/announcements/create': typeof CommonAnnouncementsCreateRoute
  '/community/create': typeof CommonCommunityCreateRoute
  '/community/edit': typeof CommonCommunityEditRoute
  '/polls/$pollId': typeof CommonPollsPollIdRoute
  '/results/$rollNo': typeof CommonResultsRollNoRoute
  '/schedules/$': typeof CommonSchedulesSplatRoute
  '/syllabus/$code': typeof CommonSyllabusCodeRoute
  '/u/$username': typeof CommonUUsernameRoute
  '/whisper-room/whisper': typeof CommonWhisperRoomWhisperRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$': typeof ApiCommentsSplatRoute
  '/api/hostel/allotment-slot': typeof ApiHostelAllotmentSlotRoute
  '/api/hostel/room-members': typeof ApiHostelRoomMembersRoute
  '/api/outpass/list': typeof ApiOutpassListRoute
  '/api/outpass/status': typeof ApiOutpassStatusRoute
  '/programs/builder-club/apply-now': typeof ProgramsBuilderClubApplyNowRoute
  '/$moderator/attendance-personal/': typeof ModeratorAttendancePersonalIndexRoute
  '/$moderator/courses/': typeof ModeratorCoursesIndexRoute
  '/$moderator/events/': typeof ModeratorEventsIndexRoute
  '/$moderator/hostels/': typeof ModeratorHostelsIndexRoute
  '/$moderator/outpass/': typeof ModeratorOutpassIndexRoute
  '/$moderator/result/': typeof ModeratorResultIndexRoute
  '/$moderator/rooms/': typeof ModeratorRoomsIndexRoute
  '/$moderator/schedules/': typeof ModeratorSchedulesIndexRoute
  '/$moderator/settings/': typeof ModeratorSettingsIndexRoute
  '/$moderator/users/': typeof ModeratorUsersIndexRoute
  '/announcements/': typeof CommonAnnouncementsIndexRoute
  '/community/': typeof CommonCommunityIndexRoute
  '/polls/': typeof CommonPollsIndexRoute
  '/resources/': typeof CommonResourcesIndexRoute
  '/results/': typeof CommonResultsIndexRoute
  '/schedules/': typeof CommonSchedulesIndexRoute
  '/syllabus/': typeof CommonSyllabusIndexRoute
  '/whisper-room/': typeof CommonWhisperRoomIndexRoute
  '/programs/builder-club/': typeof ProgramsBuilderClubIndexRoute
  '/$moderator/events/$id/edit': typeof ModeratorEventsIdEditRoute
  '/$moderator/h/$slug/allotment': typeof ModeratorHSlugAllotmentRoute
  '/$moderator/h/$slug/allotment-by-excel': typeof ModeratorHSlugAllotmentByExcelRoute
  '/$moderator/h/$slug/outpass-requests': typeof ModeratorHSlugOutpassRequestsRoute
  '/$moderator/h/$slug/rooms': typeof ModeratorHSlugRoomsRoute
  '/$moderator/h/$slug/students': typeof ModeratorHSlugStudentsRoute
  '/community/posts/$postId': typeof CommonCommunityPostsPostIdRoute
  '/resources/$type/$slug': typeof CommonResourcesTypeSlugRoute
  '/resources/stories/$id': typeof CommonResourcesStoriesIdRoute
  '/resources/stories/share': typeof CommonResourcesStoriesShareRoute
  '/$moderator/events/$id/': typeof ModeratorEventsIdIndexRoute
  '/$moderator/h/$slug/': typeof ModeratorHSlugIndexRoute
  '/resources/$type/': typeof CommonResourcesTypeIndexRoute
  '/whisper-room/feed/': typeof CommonWhisperRoomFeedIndexRoute
  '/$moderator/h/$slug/outpass-logs/$studentId': typeof ModeratorHSlugOutpassLogsStudentIdRoute
  '/whisper-room/feed/$postId/edit': typeof CommonWhisperRoomFeedPostIdEditRoute
  '/$moderator/h/$slug/outpass-logs/': typeof ModeratorHSlugOutpassLogsIndexRoute
  '/whisper-room/feed/$postId/': typeof CommonWhisperRoomFeedPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/$moderator/classes': typeof ModeratorClassesRoute
  '/$moderator/classroom': typeof ModeratorClassroomRoute
  '/$moderator/hostel-room-allotment': typeof ModeratorHostelRoomAllotmentRoute
  '/$moderator/test': typeof ModeratorTestRoute
  '/$moderator/testing': typeof ModeratorTestingRoute
  '/about': typeof CommonAboutRoute
  '/academic-calendar': typeof CommonAcademicCalendarRoute
  '/benefits': typeof CommonBenefitsRoute
  '/chat': typeof CommonChatRoute
  '/classroom-availability': typeof CommonClassroomAvailabilityRoute
  '/contact': typeof CommonContactRoute
  '/privacy-policy': typeof CommonPrivacyPolicyRoute
  '/terms': typeof CommonTermsRoute
  '/api': typeof ApiImageRoute
  '/api/experiment': typeof ApiExperimentRoute
  '/api/parsing': typeof ApiParsingRoute
  '/api/stats': typeof ApiStatsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify-mail': typeof AuthVerifyMailRoute
  '/og/$': typeof OgSplatRoute
  '/$moderator': typeof ModeratorIndexRoute
  '/': typeof CommonIndexRoute
  '/design': typeof DesignIndexRoute
  '/$moderator/attendance-personal/$id': typeof ModeratorAttendancePersonalIdRoute
  '/$moderator/courses/$courseCode': typeof ModeratorCoursesCourseCodeRoute
  '/$moderator/courses/create': typeof ModeratorCoursesCreateRoute
  '/$moderator/events/new': typeof ModeratorEventsNewRoute
  '/$moderator/hostels/$slug': typeof ModeratorHostelsSlugRoute
  '/$moderator/outpass/$id': typeof ModeratorOutpassIdRoute
  '/$moderator/outpass/request': typeof ModeratorOutpassRequestRoute
  '/$moderator/result/import': typeof ModeratorResultImportRoute
  '/$moderator/result/scraping': typeof ModeratorResultScrapingRoute
  '/$moderator/rooms/new': typeof ModeratorRoomsNewRoute
  '/$moderator/schedules/$': typeof ModeratorSchedulesSplatRoute
  '/$moderator/schedules/create': typeof ModeratorSchedulesCreateRoute
  '/$moderator/settings/account': typeof ModeratorSettingsAccountRoute
  '/$moderator/settings/appearance': typeof ModeratorSettingsAppearanceRoute
  '/$moderator/users/$id': typeof ModeratorUsersIdRoute
  '/$moderator/users/new': typeof ModeratorUsersNewRoute
  '/announcements/create': typeof CommonAnnouncementsCreateRoute
  '/community/create': typeof CommonCommunityCreateRoute
  '/community/edit': typeof CommonCommunityEditRoute
  '/polls/$pollId': typeof CommonPollsPollIdRoute
  '/results/$rollNo': typeof CommonResultsRollNoRoute
  '/schedules/$': typeof CommonSchedulesSplatRoute
  '/syllabus/$code': typeof CommonSyllabusCodeRoute
  '/u/$username': typeof CommonUUsernameRoute
  '/whisper-room/whisper': typeof CommonWhisperRoomWhisperRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$': typeof ApiCommentsSplatRoute
  '/api/hostel/allotment-slot': typeof ApiHostelAllotmentSlotRoute
  '/api/hostel/room-members': typeof ApiHostelRoomMembersRoute
  '/api/outpass/list': typeof ApiOutpassListRoute
  '/api/outpass/status': typeof ApiOutpassStatusRoute
  '/programs/builder-club/apply-now': typeof ProgramsBuilderClubApplyNowRoute
  '/$moderator/attendance-personal': typeof ModeratorAttendancePersonalIndexRoute
  '/$moderator/courses': typeof ModeratorCoursesIndexRoute
  '/$moderator/events': typeof ModeratorEventsIndexRoute
  '/$moderator/hostels': typeof ModeratorHostelsIndexRoute
  '/$moderator/outpass': typeof ModeratorOutpassIndexRoute
  '/$moderator/result': typeof ModeratorResultIndexRoute
  '/$moderator/rooms': typeof ModeratorRoomsIndexRoute
  '/$moderator/schedules': typeof ModeratorSchedulesIndexRoute
  '/$moderator/settings': typeof ModeratorSettingsIndexRoute
  '/$moderator/users': typeof ModeratorUsersIndexRoute
  '/announcements': typeof CommonAnnouncementsIndexRoute
  '/community': typeof CommonCommunityIndexRoute
  '/polls': typeof CommonPollsIndexRoute
  '/resources': typeof CommonResourcesIndexRoute
  '/results': typeof CommonResultsIndexRoute
  '/schedules': typeof CommonSchedulesIndexRoute
  '/syllabus': typeof CommonSyllabusIndexRoute
  '/whisper-room': typeof CommonWhisperRoomIndexRoute
  '/programs/builder-club': typeof ProgramsBuilderClubIndexRoute
  '/$moderator/events/$id/edit': typeof ModeratorEventsIdEditRoute
  '/$moderator/h/$slug/allotment': typeof ModeratorHSlugAllotmentRoute
  '/$moderator/h/$slug/allotment-by-excel': typeof ModeratorHSlugAllotmentByExcelRoute
  '/$moderator/h/$slug/outpass-requests': typeof ModeratorHSlugOutpassRequestsRoute
  '/$moderator/h/$slug/rooms': typeof ModeratorHSlugRoomsRoute
  '/$moderator/h/$slug/students': typeof ModeratorHSlugStudentsRoute
  '/community/posts/$postId': typeof CommonCommunityPostsPostIdRoute
  '/resources/$type/$slug': typeof CommonResourcesTypeSlugRoute
  '/resources/stories/$id': typeof CommonResourcesStoriesIdRoute
  '/resources/stories/share': typeof CommonResourcesStoriesShareRoute
  '/$moderator/events/$id': typeof ModeratorEventsIdIndexRoute
  '/$moderator/h/$slug': typeof ModeratorHSlugIndexRoute
  '/resources/$type': typeof CommonResourcesTypeIndexRoute
  '/whisper-room/feed': typeof CommonWhisperRoomFeedIndexRoute
  '/$moderator/h/$slug/outpass-logs/$studentId': typeof ModeratorHSlugOutpassLogsStudentIdRoute
  '/whisper-room/feed/$postId/edit': typeof CommonWhisperRoomFeedPostIdEditRoute
  '/$moderator/h/$slug/outpass-logs': typeof ModeratorHSlugOutpassLogsIndexRoute
  '/whisper-room/feed/$postId': typeof CommonWhisperRoomFeedPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$moderator': typeof ModeratorRouteWithChildren
  '/_common': typeof CommonRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/design': typeof DesignRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/$moderator/classes': typeof ModeratorClassesRoute
  '/$moderator/classroom': typeof ModeratorClassroomRoute
  '/$moderator/hostel-room-allotment': typeof ModeratorHostelRoomAllotmentRoute
  '/$moderator/hostels': typeof ModeratorHostelsRouteWithChildren
  '/$moderator/outpass': typeof ModeratorOutpassRouteWithChildren
  '/$moderator/settings': typeof ModeratorSettingsRouteWithChildren
  '/$moderator/test': typeof ModeratorTestRoute
  '/$moderator/testing': typeof ModeratorTestingRoute
  '/_common/about': typeof CommonAboutRoute
  '/_common/academic-calendar': typeof CommonAcademicCalendarRoute
  '/_common/benefits': typeof CommonBenefitsRoute
  '/_common/chat': typeof CommonChatRoute
  '/_common/classroom-availability': typeof CommonClassroomAvailabilityRoute
  '/_common/community': typeof CommonCommunityRouteWithChildren
  '/_common/contact': typeof CommonContactRoute
  '/_common/privacy-policy': typeof CommonPrivacyPolicyRoute
  '/_common/terms': typeof CommonTermsRoute
  '/_common/whisper-room': typeof CommonWhisperRoomRouteWithChildren
  '/api/_image': typeof ApiImageRoute
  '/api/experiment': typeof ApiExperimentRoute
  '/api/parsing': typeof ApiParsingRoute
  '/api/stats': typeof ApiStatsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/verify-mail': typeof AuthVerifyMailRoute
  '/og/$': typeof OgSplatRoute
  '/$moderator/': typeof ModeratorIndexRoute
  '/_common/': typeof CommonIndexRoute
  '/design/': typeof DesignIndexRoute
  '/$moderator/attendance-personal/$id': typeof ModeratorAttendancePersonalIdRoute
  '/$moderator/courses/$courseCode': typeof ModeratorCoursesCourseCodeRoute
  '/$moderator/courses/create': typeof ModeratorCoursesCreateRoute
  '/$moderator/events/new': typeof ModeratorEventsNewRoute
  '/$moderator/h/$slug': typeof ModeratorHSlugRouteWithChildren
  '/$moderator/hostels/$slug': typeof ModeratorHostelsSlugRoute
  '/$moderator/outpass/$id': typeof ModeratorOutpassIdRoute
  '/$moderator/outpass/request': typeof ModeratorOutpassRequestRoute
  '/$moderator/result/import': typeof ModeratorResultImportRoute
  '/$moderator/result/scraping': typeof ModeratorResultScrapingRoute
  '/$moderator/rooms/new': typeof ModeratorRoomsNewRoute
  '/$moderator/schedules/$': typeof ModeratorSchedulesSplatRoute
  '/$moderator/schedules/create': typeof ModeratorSchedulesCreateRoute
  '/$moderator/settings/account': typeof ModeratorSettingsAccountRoute
  '/$moderator/settings/appearance': typeof ModeratorSettingsAppearanceRoute
  '/$moderator/users/$id': typeof ModeratorUsersIdRoute
  '/$moderator/users/new': typeof ModeratorUsersNewRoute
  '/_common/announcements/create': typeof CommonAnnouncementsCreateRoute
  '/_common/community/create': typeof CommonCommunityCreateRoute
  '/_common/community/edit': typeof CommonCommunityEditRoute
  '/_common/polls/$pollId': typeof CommonPollsPollIdRoute
  '/_common/results/$rollNo': typeof CommonResultsRollNoRoute
  '/_common/schedules/$': typeof CommonSchedulesSplatRoute
  '/_common/syllabus/$code': typeof CommonSyllabusCodeRoute
  '/_common/u/$username': typeof CommonUUsernameRoute
  '/_common/whisper-room/whisper': typeof CommonWhisperRoomWhisperRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/comments/$': typeof ApiCommentsSplatRoute
  '/api/hostel/allotment-slot': typeof ApiHostelAllotmentSlotRoute
  '/api/hostel/room-members': typeof ApiHostelRoomMembersRoute
  '/api/outpass/list': typeof ApiOutpassListRoute
  '/api/outpass/status': typeof ApiOutpassStatusRoute
  '/programs/builder-club/apply-now': typeof ProgramsBuilderClubApplyNowRoute
  '/$moderator/attendance-personal/': typeof ModeratorAttendancePersonalIndexRoute
  '/$moderator/courses/': typeof ModeratorCoursesIndexRoute
  '/$moderator/events/': typeof ModeratorEventsIndexRoute
  '/$moderator/hostels/': typeof ModeratorHostelsIndexRoute
  '/$moderator/outpass/': typeof ModeratorOutpassIndexRoute
  '/$moderator/result/': typeof ModeratorResultIndexRoute
  '/$moderator/rooms/': typeof ModeratorRoomsIndexRoute
  '/$moderator/schedules/': typeof ModeratorSchedulesIndexRoute
  '/$moderator/settings/': typeof ModeratorSettingsIndexRoute
  '/$moderator/users/': typeof ModeratorUsersIndexRoute
  '/_common/announcements/': typeof CommonAnnouncementsIndexRoute
  '/_common/community/': typeof CommonCommunityIndexRoute
  '/_common/polls/': typeof CommonPollsIndexRoute
  '/_common/resources/': typeof CommonResourcesIndexRoute
  '/_common/results/': typeof CommonResultsIndexRoute
  '/_common/schedules/': typeof CommonSchedulesIndexRoute
  '/_common/syllabus/': typeof CommonSyllabusIndexRoute
  '/_common/whisper-room/': typeof CommonWhisperRoomIndexRoute
  '/programs/builder-club/': typeof ProgramsBuilderClubIndexRoute
  '/$moderator/events/$id/edit': typeof ModeratorEventsIdEditRoute
  '/$moderator/h/$slug/allotment': typeof ModeratorHSlugAllotmentRoute
  '/$moderator/h/$slug/allotment-by-excel': typeof ModeratorHSlugAllotmentByExcelRoute
  '/$moderator/h/$slug/outpass-requests': typeof ModeratorHSlugOutpassRequestsRoute
  '/$moderator/h/$slug/rooms': typeof ModeratorHSlugRoomsRoute
  '/$moderator/h/$slug/students': typeof ModeratorHSlugStudentsRoute
  '/_common/community/posts/$postId': typeof CommonCommunityPostsPostIdRoute
  '/_common/resources/$type/$slug': typeof CommonResourcesTypeSlugRoute
  '/_common/resources/stories/$id': typeof CommonResourcesStoriesIdRoute
  '/_common/resources/stories/share': typeof CommonResourcesStoriesShareRoute
  '/$moderator/events/$id/': typeof ModeratorEventsIdIndexRoute
  '/$moderator/h/$slug/': typeof ModeratorHSlugIndexRoute
  '/_common/resources/$type/': typeof CommonResourcesTypeIndexRoute
  '/_common/whisper-room/feed/': typeof CommonWhisperRoomFeedIndexRoute
  '/$moderator/h/$slug/outpass-logs/$studentId': typeof ModeratorHSlugOutpassLogsStudentIdRoute
  '/_common/whisper-room/feed/$postId/edit': typeof CommonWhisperRoomFeedPostIdEditRoute
  '/$moderator/h/$slug/outpass-logs/': typeof ModeratorHSlugOutpassLogsIndexRoute
  '/_common/whisper-room/feed/$postId/': typeof CommonWhisperRoomFeedPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$moderator'
    | '/'
    | '/auth'
    | '/design'
    | '/manifest.webmanifest'
    | '/programs'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/$moderator/classes'
    | '/$moderator/classroom'
    | '/$moderator/hostel-room-allotment'
    | '/$moderator/hostels'
    | '/$moderator/outpass'
    | '/$moderator/settings'
    | '/$moderator/test'
    | '/$moderator/testing'
    | '/about'
    | '/academic-calendar'
    | '/benefits'
    | '/chat'
    | '/classroom-availability'
    | '/community'
    | '/contact'
    | '/privacy-policy'
    | '/terms'
    | '/whisper-room'
    | '/api'
    | '/api/experiment'
    | '/api/parsing'
    | '/api/stats'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/verify-mail'
    | '/og/$'
    | '/$moderator/'
    | '/design/'
    | '/$moderator/attendance-personal/$id'
    | '/$moderator/courses/$courseCode'
    | '/$moderator/courses/create'
    | '/$moderator/events/new'
    | '/$moderator/h/$slug'
    | '/$moderator/hostels/$slug'
    | '/$moderator/outpass/$id'
    | '/$moderator/outpass/request'
    | '/$moderator/result/import'
    | '/$moderator/result/scraping'
    | '/$moderator/rooms/new'
    | '/$moderator/schedules/$'
    | '/$moderator/schedules/create'
    | '/$moderator/settings/account'
    | '/$moderator/settings/appearance'
    | '/$moderator/users/$id'
    | '/$moderator/users/new'
    | '/announcements/create'
    | '/community/create'
    | '/community/edit'
    | '/polls/$pollId'
    | '/results/$rollNo'
    | '/schedules/$'
    | '/syllabus/$code'
    | '/u/$username'
    | '/whisper-room/whisper'
    | '/api/auth/$'
    | '/api/comments/$'
    | '/api/hostel/allotment-slot'
    | '/api/hostel/room-members'
    | '/api/outpass/list'
    | '/api/outpass/status'
    | '/programs/builder-club/apply-now'
    | '/$moderator/attendance-personal/'
    | '/$moderator/courses/'
    | '/$moderator/events/'
    | '/$moderator/hostels/'
    | '/$moderator/outpass/'
    | '/$moderator/result/'
    | '/$moderator/rooms/'
    | '/$moderator/schedules/'
    | '/$moderator/settings/'
    | '/$moderator/users/'
    | '/announcements/'
    | '/community/'
    | '/polls/'
    | '/resources/'
    | '/results/'
    | '/schedules/'
    | '/syllabus/'
    | '/whisper-room/'
    | '/programs/builder-club/'
    | '/$moderator/events/$id/edit'
    | '/$moderator/h/$slug/allotment'
    | '/$moderator/h/$slug/allotment-by-excel'
    | '/$moderator/h/$slug/outpass-requests'
    | '/$moderator/h/$slug/rooms'
    | '/$moderator/h/$slug/students'
    | '/community/posts/$postId'
    | '/resources/$type/$slug'
    | '/resources/stories/$id'
    | '/resources/stories/share'
    | '/$moderator/events/$id/'
    | '/$moderator/h/$slug/'
    | '/resources/$type/'
    | '/whisper-room/feed/'
    | '/$moderator/h/$slug/outpass-logs/$studentId'
    | '/whisper-room/feed/$postId/edit'
    | '/$moderator/h/$slug/outpass-logs/'
    | '/whisper-room/feed/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/manifest.webmanifest'
    | '/programs'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/$moderator/classes'
    | '/$moderator/classroom'
    | '/$moderator/hostel-room-allotment'
    | '/$moderator/test'
    | '/$moderator/testing'
    | '/about'
    | '/academic-calendar'
    | '/benefits'
    | '/chat'
    | '/classroom-availability'
    | '/contact'
    | '/privacy-policy'
    | '/terms'
    | '/api'
    | '/api/experiment'
    | '/api/parsing'
    | '/api/stats'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/verify-mail'
    | '/og/$'
    | '/$moderator'
    | '/'
    | '/design'
    | '/$moderator/attendance-personal/$id'
    | '/$moderator/courses/$courseCode'
    | '/$moderator/courses/create'
    | '/$moderator/events/new'
    | '/$moderator/hostels/$slug'
    | '/$moderator/outpass/$id'
    | '/$moderator/outpass/request'
    | '/$moderator/result/import'
    | '/$moderator/result/scraping'
    | '/$moderator/rooms/new'
    | '/$moderator/schedules/$'
    | '/$moderator/schedules/create'
    | '/$moderator/settings/account'
    | '/$moderator/settings/appearance'
    | '/$moderator/users/$id'
    | '/$moderator/users/new'
    | '/announcements/create'
    | '/community/create'
    | '/community/edit'
    | '/polls/$pollId'
    | '/results/$rollNo'
    | '/schedules/$'
    | '/syllabus/$code'
    | '/u/$username'
    | '/whisper-room/whisper'
    | '/api/auth/$'
    | '/api/comments/$'
    | '/api/hostel/allotment-slot'
    | '/api/hostel/room-members'
    | '/api/outpass/list'
    | '/api/outpass/status'
    | '/programs/builder-club/apply-now'
    | '/$moderator/attendance-personal'
    | '/$moderator/courses'
    | '/$moderator/events'
    | '/$moderator/hostels'
    | '/$moderator/outpass'
    | '/$moderator/result'
    | '/$moderator/rooms'
    | '/$moderator/schedules'
    | '/$moderator/settings'
    | '/$moderator/users'
    | '/announcements'
    | '/community'
    | '/polls'
    | '/resources'
    | '/results'
    | '/schedules'
    | '/syllabus'
    | '/whisper-room'
    | '/programs/builder-club'
    | '/$moderator/events/$id/edit'
    | '/$moderator/h/$slug/allotment'
    | '/$moderator/h/$slug/allotment-by-excel'
    | '/$moderator/h/$slug/outpass-requests'
    | '/$moderator/h/$slug/rooms'
    | '/$moderator/h/$slug/students'
    | '/community/posts/$postId'
    | '/resources/$type/$slug'
    | '/resources/stories/$id'
    | '/resources/stories/share'
    | '/$moderator/events/$id'
    | '/$moderator/h/$slug'
    | '/resources/$type'
    | '/whisper-room/feed'
    | '/$moderator/h/$slug/outpass-logs/$studentId'
    | '/whisper-room/feed/$postId/edit'
    | '/$moderator/h/$slug/outpass-logs'
    | '/whisper-room/feed/$postId'
  id:
    | '__root__'
    | '/$moderator'
    | '/_common'
    | '/auth'
    | '/design'
    | '/manifest.webmanifest'
    | '/programs'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/$moderator/classes'
    | '/$moderator/classroom'
    | '/$moderator/hostel-room-allotment'
    | '/$moderator/hostels'
    | '/$moderator/outpass'
    | '/$moderator/settings'
    | '/$moderator/test'
    | '/$moderator/testing'
    | '/_common/about'
    | '/_common/academic-calendar'
    | '/_common/benefits'
    | '/_common/chat'
    | '/_common/classroom-availability'
    | '/_common/community'
    | '/_common/contact'
    | '/_common/privacy-policy'
    | '/_common/terms'
    | '/_common/whisper-room'
    | '/api/_image'
    | '/api/experiment'
    | '/api/parsing'
    | '/api/stats'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/verify-mail'
    | '/og/$'
    | '/$moderator/'
    | '/_common/'
    | '/design/'
    | '/$moderator/attendance-personal/$id'
    | '/$moderator/courses/$courseCode'
    | '/$moderator/courses/create'
    | '/$moderator/events/new'
    | '/$moderator/h/$slug'
    | '/$moderator/hostels/$slug'
    | '/$moderator/outpass/$id'
    | '/$moderator/outpass/request'
    | '/$moderator/result/import'
    | '/$moderator/result/scraping'
    | '/$moderator/rooms/new'
    | '/$moderator/schedules/$'
    | '/$moderator/schedules/create'
    | '/$moderator/settings/account'
    | '/$moderator/settings/appearance'
    | '/$moderator/users/$id'
    | '/$moderator/users/new'
    | '/_common/announcements/create'
    | '/_common/community/create'
    | '/_common/community/edit'
    | '/_common/polls/$pollId'
    | '/_common/results/$rollNo'
    | '/_common/schedules/$'
    | '/_common/syllabus/$code'
    | '/_common/u/$username'
    | '/_common/whisper-room/whisper'
    | '/api/auth/$'
    | '/api/comments/$'
    | '/api/hostel/allotment-slot'
    | '/api/hostel/room-members'
    | '/api/outpass/list'
    | '/api/outpass/status'
    | '/programs/builder-club/apply-now'
    | '/$moderator/attendance-personal/'
    | '/$moderator/courses/'
    | '/$moderator/events/'
    | '/$moderator/hostels/'
    | '/$moderator/outpass/'
    | '/$moderator/result/'
    | '/$moderator/rooms/'
    | '/$moderator/schedules/'
    | '/$moderator/settings/'
    | '/$moderator/users/'
    | '/_common/announcements/'
    | '/_common/community/'
    | '/_common/polls/'
    | '/_common/resources/'
    | '/_common/results/'
    | '/_common/schedules/'
    | '/_common/syllabus/'
    | '/_common/whisper-room/'
    | '/programs/builder-club/'
    | '/$moderator/events/$id/edit'
    | '/$moderator/h/$slug/allotment'
    | '/$moderator/h/$slug/allotment-by-excel'
    | '/$moderator/h/$slug/outpass-requests'
    | '/$moderator/h/$slug/rooms'
    | '/$moderator/h/$slug/students'
    | '/_common/community/posts/$postId'
    | '/_common/resources/$type/$slug'
    | '/_common/resources/stories/$id'
    | '/_common/resources/stories/share'
    | '/$moderator/events/$id/'
    | '/$moderator/h/$slug/'
    | '/_common/resources/$type/'
    | '/_common/whisper-room/feed/'
    | '/$moderator/h/$slug/outpass-logs/$studentId'
    | '/_common/whisper-room/feed/$postId/edit'
    | '/$moderator/h/$slug/outpass-logs/'
    | '/_common/whisper-room/feed/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ModeratorRoute: typeof ModeratorRouteWithChildren
  CommonRoute: typeof CommonRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DesignRoute: typeof DesignRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiExperimentRoute: typeof ApiExperimentRoute
  ApiParsingRoute: typeof ApiParsingRoute
  ApiStatsRoute: typeof ApiStatsRoute
  OgSplatRoute: typeof OgSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCommentsSplatRoute: typeof ApiCommentsSplatRoute
  ApiHostelAllotmentSlotRoute: typeof ApiHostelAllotmentSlotRoute
  ApiHostelRoomMembersRoute: typeof ApiHostelRoomMembersRoute
  ApiOutpassListRoute: typeof ApiOutpassListRoute
  ApiOutpassStatusRoute: typeof ApiOutpassStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_common': {
      id: '/_common'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CommonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$moderator': {
      id: '/$moderator'
      path: '/$moderator'
      fullPath: '/$moderator'
      preLoaderRoute: typeof ModeratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/': {
      id: '/design/'
      path: '/'
      fullPath: '/design/'
      preLoaderRoute: typeof DesignIndexRouteImport
      parentRoute: typeof DesignRoute
    }
    '/_common/': {
      id: '/_common/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CommonIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/$moderator/': {
      id: '/$moderator/'
      path: '/'
      fullPath: '/$moderator/'
      preLoaderRoute: typeof ModeratorIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/og/$': {
      id: '/og/$'
      path: '/og/$'
      fullPath: '/og/$'
      preLoaderRoute: typeof OgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-mail': {
      id: '/auth/verify-mail'
      path: '/verify-mail'
      fullPath: '/auth/verify-mail'
      preLoaderRoute: typeof AuthVerifyMailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parsing': {
      id: '/api/parsing'
      path: '/api/parsing'
      fullPath: '/api/parsing'
      preLoaderRoute: typeof ApiParsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/experiment': {
      id: '/api/experiment'
      path: '/api/experiment'
      fullPath: '/api/experiment'
      preLoaderRoute: typeof ApiExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/_image': {
      id: '/api/_image'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_common/whisper-room': {
      id: '/_common/whisper-room'
      path: '/whisper-room'
      fullPath: '/whisper-room'
      preLoaderRoute: typeof CommonWhisperRoomRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/terms': {
      id: '/_common/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof CommonTermsRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/privacy-policy': {
      id: '/_common/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof CommonPrivacyPolicyRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/contact': {
      id: '/_common/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof CommonContactRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/community': {
      id: '/_common/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommonCommunityRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/classroom-availability': {
      id: '/_common/classroom-availability'
      path: '/classroom-availability'
      fullPath: '/classroom-availability'
      preLoaderRoute: typeof CommonClassroomAvailabilityRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/chat': {
      id: '/_common/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof CommonChatRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/benefits': {
      id: '/_common/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof CommonBenefitsRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/academic-calendar': {
      id: '/_common/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof CommonAcademicCalendarRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/about': {
      id: '/_common/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof CommonAboutRouteImport
      parentRoute: typeof CommonRoute
    }
    '/$moderator/testing': {
      id: '/$moderator/testing'
      path: '/testing'
      fullPath: '/$moderator/testing'
      preLoaderRoute: typeof ModeratorTestingRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/test': {
      id: '/$moderator/test'
      path: '/test'
      fullPath: '/$moderator/test'
      preLoaderRoute: typeof ModeratorTestRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/settings': {
      id: '/$moderator/settings'
      path: '/settings'
      fullPath: '/$moderator/settings'
      preLoaderRoute: typeof ModeratorSettingsRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/outpass': {
      id: '/$moderator/outpass'
      path: '/outpass'
      fullPath: '/$moderator/outpass'
      preLoaderRoute: typeof ModeratorOutpassRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/hostels': {
      id: '/$moderator/hostels'
      path: '/hostels'
      fullPath: '/$moderator/hostels'
      preLoaderRoute: typeof ModeratorHostelsRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/hostel-room-allotment': {
      id: '/$moderator/hostel-room-allotment'
      path: '/hostel-room-allotment'
      fullPath: '/$moderator/hostel-room-allotment'
      preLoaderRoute: typeof ModeratorHostelRoomAllotmentRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/classroom': {
      id: '/$moderator/classroom'
      path: '/classroom'
      fullPath: '/$moderator/classroom'
      preLoaderRoute: typeof ModeratorClassroomRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/classes': {
      id: '/$moderator/classes'
      path: '/classes'
      fullPath: '/$moderator/classes'
      preLoaderRoute: typeof ModeratorClassesRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/programs/builder-club/': {
      id: '/programs/builder-club/'
      path: '/builder-club'
      fullPath: '/programs/builder-club/'
      preLoaderRoute: typeof ProgramsBuilderClubIndexRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/_common/whisper-room/': {
      id: '/_common/whisper-room/'
      path: '/'
      fullPath: '/whisper-room/'
      preLoaderRoute: typeof CommonWhisperRoomIndexRouteImport
      parentRoute: typeof CommonWhisperRoomRoute
    }
    '/_common/syllabus/': {
      id: '/_common/syllabus/'
      path: '/syllabus'
      fullPath: '/syllabus/'
      preLoaderRoute: typeof CommonSyllabusIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/schedules/': {
      id: '/_common/schedules/'
      path: '/schedules'
      fullPath: '/schedules/'
      preLoaderRoute: typeof CommonSchedulesIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/results/': {
      id: '/_common/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof CommonResultsIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/resources/': {
      id: '/_common/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof CommonResourcesIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/polls/': {
      id: '/_common/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof CommonPollsIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/community/': {
      id: '/_common/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommonCommunityIndexRouteImport
      parentRoute: typeof CommonCommunityRoute
    }
    '/_common/announcements/': {
      id: '/_common/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof CommonAnnouncementsIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/$moderator/users/': {
      id: '/$moderator/users/'
      path: '/users'
      fullPath: '/$moderator/users/'
      preLoaderRoute: typeof ModeratorUsersIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/settings/': {
      id: '/$moderator/settings/'
      path: '/'
      fullPath: '/$moderator/settings/'
      preLoaderRoute: typeof ModeratorSettingsIndexRouteImport
      parentRoute: typeof ModeratorSettingsRoute
    }
    '/$moderator/schedules/': {
      id: '/$moderator/schedules/'
      path: '/schedules'
      fullPath: '/$moderator/schedules/'
      preLoaderRoute: typeof ModeratorSchedulesIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/rooms/': {
      id: '/$moderator/rooms/'
      path: '/rooms'
      fullPath: '/$moderator/rooms/'
      preLoaderRoute: typeof ModeratorRoomsIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/result/': {
      id: '/$moderator/result/'
      path: '/result'
      fullPath: '/$moderator/result/'
      preLoaderRoute: typeof ModeratorResultIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/outpass/': {
      id: '/$moderator/outpass/'
      path: '/'
      fullPath: '/$moderator/outpass/'
      preLoaderRoute: typeof ModeratorOutpassIndexRouteImport
      parentRoute: typeof ModeratorOutpassRoute
    }
    '/$moderator/hostels/': {
      id: '/$moderator/hostels/'
      path: '/'
      fullPath: '/$moderator/hostels/'
      preLoaderRoute: typeof ModeratorHostelsIndexRouteImport
      parentRoute: typeof ModeratorHostelsRoute
    }
    '/$moderator/events/': {
      id: '/$moderator/events/'
      path: '/events'
      fullPath: '/$moderator/events/'
      preLoaderRoute: typeof ModeratorEventsIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/courses/': {
      id: '/$moderator/courses/'
      path: '/courses'
      fullPath: '/$moderator/courses/'
      preLoaderRoute: typeof ModeratorCoursesIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/attendance-personal/': {
      id: '/$moderator/attendance-personal/'
      path: '/attendance-personal'
      fullPath: '/$moderator/attendance-personal/'
      preLoaderRoute: typeof ModeratorAttendancePersonalIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/programs/builder-club/apply-now': {
      id: '/programs/builder-club/apply-now'
      path: '/builder-club/apply-now'
      fullPath: '/programs/builder-club/apply-now'
      preLoaderRoute: typeof ProgramsBuilderClubApplyNowRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/api/outpass/status': {
      id: '/api/outpass/status'
      path: '/api/outpass/status'
      fullPath: '/api/outpass/status'
      preLoaderRoute: typeof ApiOutpassStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/outpass/list': {
      id: '/api/outpass/list'
      path: '/api/outpass/list'
      fullPath: '/api/outpass/list'
      preLoaderRoute: typeof ApiOutpassListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hostel/room-members': {
      id: '/api/hostel/room-members'
      path: '/api/hostel/room-members'
      fullPath: '/api/hostel/room-members'
      preLoaderRoute: typeof ApiHostelRoomMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hostel/allotment-slot': {
      id: '/api/hostel/allotment-slot'
      path: '/api/hostel/allotment-slot'
      fullPath: '/api/hostel/allotment-slot'
      preLoaderRoute: typeof ApiHostelAllotmentSlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments/$': {
      id: '/api/comments/$'
      path: '/api/comments/$'
      fullPath: '/api/comments/$'
      preLoaderRoute: typeof ApiCommentsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_common/whisper-room/whisper': {
      id: '/_common/whisper-room/whisper'
      path: '/whisper'
      fullPath: '/whisper-room/whisper'
      preLoaderRoute: typeof CommonWhisperRoomWhisperRouteImport
      parentRoute: typeof CommonWhisperRoomRoute
    }
    '/_common/u/$username': {
      id: '/_common/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof CommonUUsernameRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/syllabus/$code': {
      id: '/_common/syllabus/$code'
      path: '/syllabus/$code'
      fullPath: '/syllabus/$code'
      preLoaderRoute: typeof CommonSyllabusCodeRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/schedules/$': {
      id: '/_common/schedules/$'
      path: '/schedules/$'
      fullPath: '/schedules/$'
      preLoaderRoute: typeof CommonSchedulesSplatRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/results/$rollNo': {
      id: '/_common/results/$rollNo'
      path: '/results/$rollNo'
      fullPath: '/results/$rollNo'
      preLoaderRoute: typeof CommonResultsRollNoRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/polls/$pollId': {
      id: '/_common/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof CommonPollsPollIdRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/community/edit': {
      id: '/_common/community/edit'
      path: '/edit'
      fullPath: '/community/edit'
      preLoaderRoute: typeof CommonCommunityEditRouteImport
      parentRoute: typeof CommonCommunityRoute
    }
    '/_common/community/create': {
      id: '/_common/community/create'
      path: '/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof CommonCommunityCreateRouteImport
      parentRoute: typeof CommonCommunityRoute
    }
    '/_common/announcements/create': {
      id: '/_common/announcements/create'
      path: '/announcements/create'
      fullPath: '/announcements/create'
      preLoaderRoute: typeof CommonAnnouncementsCreateRouteImport
      parentRoute: typeof CommonRoute
    }
    '/$moderator/users/new': {
      id: '/$moderator/users/new'
      path: '/users/new'
      fullPath: '/$moderator/users/new'
      preLoaderRoute: typeof ModeratorUsersNewRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/users/$id': {
      id: '/$moderator/users/$id'
      path: '/users/$id'
      fullPath: '/$moderator/users/$id'
      preLoaderRoute: typeof ModeratorUsersIdRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/settings/appearance': {
      id: '/$moderator/settings/appearance'
      path: '/appearance'
      fullPath: '/$moderator/settings/appearance'
      preLoaderRoute: typeof ModeratorSettingsAppearanceRouteImport
      parentRoute: typeof ModeratorSettingsRoute
    }
    '/$moderator/settings/account': {
      id: '/$moderator/settings/account'
      path: '/account'
      fullPath: '/$moderator/settings/account'
      preLoaderRoute: typeof ModeratorSettingsAccountRouteImport
      parentRoute: typeof ModeratorSettingsRoute
    }
    '/$moderator/schedules/create': {
      id: '/$moderator/schedules/create'
      path: '/schedules/create'
      fullPath: '/$moderator/schedules/create'
      preLoaderRoute: typeof ModeratorSchedulesCreateRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/schedules/$': {
      id: '/$moderator/schedules/$'
      path: '/schedules/$'
      fullPath: '/$moderator/schedules/$'
      preLoaderRoute: typeof ModeratorSchedulesSplatRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/rooms/new': {
      id: '/$moderator/rooms/new'
      path: '/rooms/new'
      fullPath: '/$moderator/rooms/new'
      preLoaderRoute: typeof ModeratorRoomsNewRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/result/scraping': {
      id: '/$moderator/result/scraping'
      path: '/result/scraping'
      fullPath: '/$moderator/result/scraping'
      preLoaderRoute: typeof ModeratorResultScrapingRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/result/import': {
      id: '/$moderator/result/import'
      path: '/result/import'
      fullPath: '/$moderator/result/import'
      preLoaderRoute: typeof ModeratorResultImportRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/outpass/request': {
      id: '/$moderator/outpass/request'
      path: '/request'
      fullPath: '/$moderator/outpass/request'
      preLoaderRoute: typeof ModeratorOutpassRequestRouteImport
      parentRoute: typeof ModeratorOutpassRoute
    }
    '/$moderator/outpass/$id': {
      id: '/$moderator/outpass/$id'
      path: '/$id'
      fullPath: '/$moderator/outpass/$id'
      preLoaderRoute: typeof ModeratorOutpassIdRouteImport
      parentRoute: typeof ModeratorOutpassRoute
    }
    '/$moderator/hostels/$slug': {
      id: '/$moderator/hostels/$slug'
      path: '/$slug'
      fullPath: '/$moderator/hostels/$slug'
      preLoaderRoute: typeof ModeratorHostelsSlugRouteImport
      parentRoute: typeof ModeratorHostelsRoute
    }
    '/$moderator/h/$slug': {
      id: '/$moderator/h/$slug'
      path: '/h/$slug'
      fullPath: '/$moderator/h/$slug'
      preLoaderRoute: typeof ModeratorHSlugRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/events/new': {
      id: '/$moderator/events/new'
      path: '/events/new'
      fullPath: '/$moderator/events/new'
      preLoaderRoute: typeof ModeratorEventsNewRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/courses/create': {
      id: '/$moderator/courses/create'
      path: '/courses/create'
      fullPath: '/$moderator/courses/create'
      preLoaderRoute: typeof ModeratorCoursesCreateRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/courses/$courseCode': {
      id: '/$moderator/courses/$courseCode'
      path: '/courses/$courseCode'
      fullPath: '/$moderator/courses/$courseCode'
      preLoaderRoute: typeof ModeratorCoursesCourseCodeRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/$moderator/attendance-personal/$id': {
      id: '/$moderator/attendance-personal/$id'
      path: '/attendance-personal/$id'
      fullPath: '/$moderator/attendance-personal/$id'
      preLoaderRoute: typeof ModeratorAttendancePersonalIdRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_common/whisper-room/feed/': {
      id: '/_common/whisper-room/feed/'
      path: '/feed'
      fullPath: '/whisper-room/feed/'
      preLoaderRoute: typeof CommonWhisperRoomFeedIndexRouteImport
      parentRoute: typeof CommonWhisperRoomRoute
    }
    '/_common/resources/$type/': {
      id: '/_common/resources/$type/'
      path: '/resources/$type'
      fullPath: '/resources/$type/'
      preLoaderRoute: typeof CommonResourcesTypeIndexRouteImport
      parentRoute: typeof CommonRoute
    }
    '/$moderator/h/$slug/': {
      id: '/$moderator/h/$slug/'
      path: '/'
      fullPath: '/$moderator/h/$slug/'
      preLoaderRoute: typeof ModeratorHSlugIndexRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/$moderator/events/$id/': {
      id: '/$moderator/events/$id/'
      path: '/events/$id'
      fullPath: '/$moderator/events/$id/'
      preLoaderRoute: typeof ModeratorEventsIdIndexRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_common/resources/stories/share': {
      id: '/_common/resources/stories/share'
      path: '/resources/stories/share'
      fullPath: '/resources/stories/share'
      preLoaderRoute: typeof CommonResourcesStoriesShareRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/resources/stories/$id': {
      id: '/_common/resources/stories/$id'
      path: '/resources/stories/$id'
      fullPath: '/resources/stories/$id'
      preLoaderRoute: typeof CommonResourcesStoriesIdRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/resources/$type/$slug': {
      id: '/_common/resources/$type/$slug'
      path: '/resources/$type/$slug'
      fullPath: '/resources/$type/$slug'
      preLoaderRoute: typeof CommonResourcesTypeSlugRouteImport
      parentRoute: typeof CommonRoute
    }
    '/_common/community/posts/$postId': {
      id: '/_common/community/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/community/posts/$postId'
      preLoaderRoute: typeof CommonCommunityPostsPostIdRouteImport
      parentRoute: typeof CommonCommunityRoute
    }
    '/$moderator/h/$slug/students': {
      id: '/$moderator/h/$slug/students'
      path: '/students'
      fullPath: '/$moderator/h/$slug/students'
      preLoaderRoute: typeof ModeratorHSlugStudentsRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/$moderator/h/$slug/rooms': {
      id: '/$moderator/h/$slug/rooms'
      path: '/rooms'
      fullPath: '/$moderator/h/$slug/rooms'
      preLoaderRoute: typeof ModeratorHSlugRoomsRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/$moderator/h/$slug/outpass-requests': {
      id: '/$moderator/h/$slug/outpass-requests'
      path: '/outpass-requests'
      fullPath: '/$moderator/h/$slug/outpass-requests'
      preLoaderRoute: typeof ModeratorHSlugOutpassRequestsRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/$moderator/h/$slug/allotment-by-excel': {
      id: '/$moderator/h/$slug/allotment-by-excel'
      path: '/allotment-by-excel'
      fullPath: '/$moderator/h/$slug/allotment-by-excel'
      preLoaderRoute: typeof ModeratorHSlugAllotmentByExcelRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/$moderator/h/$slug/allotment': {
      id: '/$moderator/h/$slug/allotment'
      path: '/allotment'
      fullPath: '/$moderator/h/$slug/allotment'
      preLoaderRoute: typeof ModeratorHSlugAllotmentRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/$moderator/events/$id/edit': {
      id: '/$moderator/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/$moderator/events/$id/edit'
      preLoaderRoute: typeof ModeratorEventsIdEditRouteImport
      parentRoute: typeof ModeratorRoute
    }
    '/_common/whisper-room/feed/$postId/': {
      id: '/_common/whisper-room/feed/$postId/'
      path: '/feed/$postId'
      fullPath: '/whisper-room/feed/$postId/'
      preLoaderRoute: typeof CommonWhisperRoomFeedPostIdIndexRouteImport
      parentRoute: typeof CommonWhisperRoomRoute
    }
    '/$moderator/h/$slug/outpass-logs/': {
      id: '/$moderator/h/$slug/outpass-logs/'
      path: '/outpass-logs'
      fullPath: '/$moderator/h/$slug/outpass-logs/'
      preLoaderRoute: typeof ModeratorHSlugOutpassLogsIndexRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
    '/_common/whisper-room/feed/$postId/edit': {
      id: '/_common/whisper-room/feed/$postId/edit'
      path: '/feed/$postId/edit'
      fullPath: '/whisper-room/feed/$postId/edit'
      preLoaderRoute: typeof CommonWhisperRoomFeedPostIdEditRouteImport
      parentRoute: typeof CommonWhisperRoomRoute
    }
    '/$moderator/h/$slug/outpass-logs/$studentId': {
      id: '/$moderator/h/$slug/outpass-logs/$studentId'
      path: '/outpass-logs/$studentId'
      fullPath: '/$moderator/h/$slug/outpass-logs/$studentId'
      preLoaderRoute: typeof ModeratorHSlugOutpassLogsStudentIdRouteImport
      parentRoute: typeof ModeratorHSlugRoute
    }
  }
}

interface ModeratorHostelsRouteChildren {
  ModeratorHostelsSlugRoute: typeof ModeratorHostelsSlugRoute
  ModeratorHostelsIndexRoute: typeof ModeratorHostelsIndexRoute
}

const ModeratorHostelsRouteChildren: ModeratorHostelsRouteChildren = {
  ModeratorHostelsSlugRoute: ModeratorHostelsSlugRoute,
  ModeratorHostelsIndexRoute: ModeratorHostelsIndexRoute,
}

const ModeratorHostelsRouteWithChildren =
  ModeratorHostelsRoute._addFileChildren(ModeratorHostelsRouteChildren)

interface ModeratorOutpassRouteChildren {
  ModeratorOutpassIdRoute: typeof ModeratorOutpassIdRoute
  ModeratorOutpassRequestRoute: typeof ModeratorOutpassRequestRoute
  ModeratorOutpassIndexRoute: typeof ModeratorOutpassIndexRoute
}

const ModeratorOutpassRouteChildren: ModeratorOutpassRouteChildren = {
  ModeratorOutpassIdRoute: ModeratorOutpassIdRoute,
  ModeratorOutpassRequestRoute: ModeratorOutpassRequestRoute,
  ModeratorOutpassIndexRoute: ModeratorOutpassIndexRoute,
}

const ModeratorOutpassRouteWithChildren =
  ModeratorOutpassRoute._addFileChildren(ModeratorOutpassRouteChildren)

interface ModeratorSettingsRouteChildren {
  ModeratorSettingsAccountRoute: typeof ModeratorSettingsAccountRoute
  ModeratorSettingsAppearanceRoute: typeof ModeratorSettingsAppearanceRoute
  ModeratorSettingsIndexRoute: typeof ModeratorSettingsIndexRoute
}

const ModeratorSettingsRouteChildren: ModeratorSettingsRouteChildren = {
  ModeratorSettingsAccountRoute: ModeratorSettingsAccountRoute,
  ModeratorSettingsAppearanceRoute: ModeratorSettingsAppearanceRoute,
  ModeratorSettingsIndexRoute: ModeratorSettingsIndexRoute,
}

const ModeratorSettingsRouteWithChildren =
  ModeratorSettingsRoute._addFileChildren(ModeratorSettingsRouteChildren)

interface ModeratorHSlugRouteChildren {
  ModeratorHSlugAllotmentRoute: typeof ModeratorHSlugAllotmentRoute
  ModeratorHSlugAllotmentByExcelRoute: typeof ModeratorHSlugAllotmentByExcelRoute
  ModeratorHSlugOutpassRequestsRoute: typeof ModeratorHSlugOutpassRequestsRoute
  ModeratorHSlugRoomsRoute: typeof ModeratorHSlugRoomsRoute
  ModeratorHSlugStudentsRoute: typeof ModeratorHSlugStudentsRoute
  ModeratorHSlugIndexRoute: typeof ModeratorHSlugIndexRoute
  ModeratorHSlugOutpassLogsStudentIdRoute: typeof ModeratorHSlugOutpassLogsStudentIdRoute
  ModeratorHSlugOutpassLogsIndexRoute: typeof ModeratorHSlugOutpassLogsIndexRoute
}

const ModeratorHSlugRouteChildren: ModeratorHSlugRouteChildren = {
  ModeratorHSlugAllotmentRoute: ModeratorHSlugAllotmentRoute,
  ModeratorHSlugAllotmentByExcelRoute: ModeratorHSlugAllotmentByExcelRoute,
  ModeratorHSlugOutpassRequestsRoute: ModeratorHSlugOutpassRequestsRoute,
  ModeratorHSlugRoomsRoute: ModeratorHSlugRoomsRoute,
  ModeratorHSlugStudentsRoute: ModeratorHSlugStudentsRoute,
  ModeratorHSlugIndexRoute: ModeratorHSlugIndexRoute,
  ModeratorHSlugOutpassLogsStudentIdRoute:
    ModeratorHSlugOutpassLogsStudentIdRoute,
  ModeratorHSlugOutpassLogsIndexRoute: ModeratorHSlugOutpassLogsIndexRoute,
}

const ModeratorHSlugRouteWithChildren = ModeratorHSlugRoute._addFileChildren(
  ModeratorHSlugRouteChildren,
)

interface ModeratorRouteChildren {
  ModeratorClassesRoute: typeof ModeratorClassesRoute
  ModeratorClassroomRoute: typeof ModeratorClassroomRoute
  ModeratorHostelRoomAllotmentRoute: typeof ModeratorHostelRoomAllotmentRoute
  ModeratorHostelsRoute: typeof ModeratorHostelsRouteWithChildren
  ModeratorOutpassRoute: typeof ModeratorOutpassRouteWithChildren
  ModeratorSettingsRoute: typeof ModeratorSettingsRouteWithChildren
  ModeratorTestRoute: typeof ModeratorTestRoute
  ModeratorTestingRoute: typeof ModeratorTestingRoute
  ModeratorIndexRoute: typeof ModeratorIndexRoute
  ModeratorAttendancePersonalIdRoute: typeof ModeratorAttendancePersonalIdRoute
  ModeratorCoursesCourseCodeRoute: typeof ModeratorCoursesCourseCodeRoute
  ModeratorCoursesCreateRoute: typeof ModeratorCoursesCreateRoute
  ModeratorEventsNewRoute: typeof ModeratorEventsNewRoute
  ModeratorHSlugRoute: typeof ModeratorHSlugRouteWithChildren
  ModeratorResultImportRoute: typeof ModeratorResultImportRoute
  ModeratorResultScrapingRoute: typeof ModeratorResultScrapingRoute
  ModeratorRoomsNewRoute: typeof ModeratorRoomsNewRoute
  ModeratorSchedulesSplatRoute: typeof ModeratorSchedulesSplatRoute
  ModeratorSchedulesCreateRoute: typeof ModeratorSchedulesCreateRoute
  ModeratorUsersIdRoute: typeof ModeratorUsersIdRoute
  ModeratorUsersNewRoute: typeof ModeratorUsersNewRoute
  ModeratorAttendancePersonalIndexRoute: typeof ModeratorAttendancePersonalIndexRoute
  ModeratorCoursesIndexRoute: typeof ModeratorCoursesIndexRoute
  ModeratorEventsIndexRoute: typeof ModeratorEventsIndexRoute
  ModeratorResultIndexRoute: typeof ModeratorResultIndexRoute
  ModeratorRoomsIndexRoute: typeof ModeratorRoomsIndexRoute
  ModeratorSchedulesIndexRoute: typeof ModeratorSchedulesIndexRoute
  ModeratorUsersIndexRoute: typeof ModeratorUsersIndexRoute
  ModeratorEventsIdEditRoute: typeof ModeratorEventsIdEditRoute
  ModeratorEventsIdIndexRoute: typeof ModeratorEventsIdIndexRoute
}

const ModeratorRouteChildren: ModeratorRouteChildren = {
  ModeratorClassesRoute: ModeratorClassesRoute,
  ModeratorClassroomRoute: ModeratorClassroomRoute,
  ModeratorHostelRoomAllotmentRoute: ModeratorHostelRoomAllotmentRoute,
  ModeratorHostelsRoute: ModeratorHostelsRouteWithChildren,
  ModeratorOutpassRoute: ModeratorOutpassRouteWithChildren,
  ModeratorSettingsRoute: ModeratorSettingsRouteWithChildren,
  ModeratorTestRoute: ModeratorTestRoute,
  ModeratorTestingRoute: ModeratorTestingRoute,
  ModeratorIndexRoute: ModeratorIndexRoute,
  ModeratorAttendancePersonalIdRoute: ModeratorAttendancePersonalIdRoute,
  ModeratorCoursesCourseCodeRoute: ModeratorCoursesCourseCodeRoute,
  ModeratorCoursesCreateRoute: ModeratorCoursesCreateRoute,
  ModeratorEventsNewRoute: ModeratorEventsNewRoute,
  ModeratorHSlugRoute: ModeratorHSlugRouteWithChildren,
  ModeratorResultImportRoute: ModeratorResultImportRoute,
  ModeratorResultScrapingRoute: ModeratorResultScrapingRoute,
  ModeratorRoomsNewRoute: ModeratorRoomsNewRoute,
  ModeratorSchedulesSplatRoute: ModeratorSchedulesSplatRoute,
  ModeratorSchedulesCreateRoute: ModeratorSchedulesCreateRoute,
  ModeratorUsersIdRoute: ModeratorUsersIdRoute,
  ModeratorUsersNewRoute: ModeratorUsersNewRoute,
  ModeratorAttendancePersonalIndexRoute: ModeratorAttendancePersonalIndexRoute,
  ModeratorCoursesIndexRoute: ModeratorCoursesIndexRoute,
  ModeratorEventsIndexRoute: ModeratorEventsIndexRoute,
  ModeratorResultIndexRoute: ModeratorResultIndexRoute,
  ModeratorRoomsIndexRoute: ModeratorRoomsIndexRoute,
  ModeratorSchedulesIndexRoute: ModeratorSchedulesIndexRoute,
  ModeratorUsersIndexRoute: ModeratorUsersIndexRoute,
  ModeratorEventsIdEditRoute: ModeratorEventsIdEditRoute,
  ModeratorEventsIdIndexRoute: ModeratorEventsIdIndexRoute,
}

const ModeratorRouteWithChildren = ModeratorRoute._addFileChildren(
  ModeratorRouteChildren,
)

interface CommonCommunityRouteChildren {
  CommonCommunityCreateRoute: typeof CommonCommunityCreateRoute
  CommonCommunityEditRoute: typeof CommonCommunityEditRoute
  CommonCommunityIndexRoute: typeof CommonCommunityIndexRoute
  CommonCommunityPostsPostIdRoute: typeof CommonCommunityPostsPostIdRoute
}

const CommonCommunityRouteChildren: CommonCommunityRouteChildren = {
  CommonCommunityCreateRoute: CommonCommunityCreateRoute,
  CommonCommunityEditRoute: CommonCommunityEditRoute,
  CommonCommunityIndexRoute: CommonCommunityIndexRoute,
  CommonCommunityPostsPostIdRoute: CommonCommunityPostsPostIdRoute,
}

const CommonCommunityRouteWithChildren = CommonCommunityRoute._addFileChildren(
  CommonCommunityRouteChildren,
)

interface CommonWhisperRoomRouteChildren {
  CommonWhisperRoomWhisperRoute: typeof CommonWhisperRoomWhisperRoute
  CommonWhisperRoomIndexRoute: typeof CommonWhisperRoomIndexRoute
  CommonWhisperRoomFeedIndexRoute: typeof CommonWhisperRoomFeedIndexRoute
  CommonWhisperRoomFeedPostIdEditRoute: typeof CommonWhisperRoomFeedPostIdEditRoute
  CommonWhisperRoomFeedPostIdIndexRoute: typeof CommonWhisperRoomFeedPostIdIndexRoute
}

const CommonWhisperRoomRouteChildren: CommonWhisperRoomRouteChildren = {
  CommonWhisperRoomWhisperRoute: CommonWhisperRoomWhisperRoute,
  CommonWhisperRoomIndexRoute: CommonWhisperRoomIndexRoute,
  CommonWhisperRoomFeedIndexRoute: CommonWhisperRoomFeedIndexRoute,
  CommonWhisperRoomFeedPostIdEditRoute: CommonWhisperRoomFeedPostIdEditRoute,
  CommonWhisperRoomFeedPostIdIndexRoute: CommonWhisperRoomFeedPostIdIndexRoute,
}

const CommonWhisperRoomRouteWithChildren =
  CommonWhisperRoomRoute._addFileChildren(CommonWhisperRoomRouteChildren)

interface CommonRouteChildren {
  CommonAboutRoute: typeof CommonAboutRoute
  CommonAcademicCalendarRoute: typeof CommonAcademicCalendarRoute
  CommonBenefitsRoute: typeof CommonBenefitsRoute
  CommonChatRoute: typeof CommonChatRoute
  CommonClassroomAvailabilityRoute: typeof CommonClassroomAvailabilityRoute
  CommonCommunityRoute: typeof CommonCommunityRouteWithChildren
  CommonContactRoute: typeof CommonContactRoute
  CommonPrivacyPolicyRoute: typeof CommonPrivacyPolicyRoute
  CommonTermsRoute: typeof CommonTermsRoute
  CommonWhisperRoomRoute: typeof CommonWhisperRoomRouteWithChildren
  CommonIndexRoute: typeof CommonIndexRoute
  CommonAnnouncementsCreateRoute: typeof CommonAnnouncementsCreateRoute
  CommonPollsPollIdRoute: typeof CommonPollsPollIdRoute
  CommonResultsRollNoRoute: typeof CommonResultsRollNoRoute
  CommonSchedulesSplatRoute: typeof CommonSchedulesSplatRoute
  CommonSyllabusCodeRoute: typeof CommonSyllabusCodeRoute
  CommonUUsernameRoute: typeof CommonUUsernameRoute
  CommonAnnouncementsIndexRoute: typeof CommonAnnouncementsIndexRoute
  CommonPollsIndexRoute: typeof CommonPollsIndexRoute
  CommonResourcesIndexRoute: typeof CommonResourcesIndexRoute
  CommonResultsIndexRoute: typeof CommonResultsIndexRoute
  CommonSchedulesIndexRoute: typeof CommonSchedulesIndexRoute
  CommonSyllabusIndexRoute: typeof CommonSyllabusIndexRoute
  CommonResourcesTypeSlugRoute: typeof CommonResourcesTypeSlugRoute
  CommonResourcesStoriesIdRoute: typeof CommonResourcesStoriesIdRoute
  CommonResourcesStoriesShareRoute: typeof CommonResourcesStoriesShareRoute
  CommonResourcesTypeIndexRoute: typeof CommonResourcesTypeIndexRoute
}

const CommonRouteChildren: CommonRouteChildren = {
  CommonAboutRoute: CommonAboutRoute,
  CommonAcademicCalendarRoute: CommonAcademicCalendarRoute,
  CommonBenefitsRoute: CommonBenefitsRoute,
  CommonChatRoute: CommonChatRoute,
  CommonClassroomAvailabilityRoute: CommonClassroomAvailabilityRoute,
  CommonCommunityRoute: CommonCommunityRouteWithChildren,
  CommonContactRoute: CommonContactRoute,
  CommonPrivacyPolicyRoute: CommonPrivacyPolicyRoute,
  CommonTermsRoute: CommonTermsRoute,
  CommonWhisperRoomRoute: CommonWhisperRoomRouteWithChildren,
  CommonIndexRoute: CommonIndexRoute,
  CommonAnnouncementsCreateRoute: CommonAnnouncementsCreateRoute,
  CommonPollsPollIdRoute: CommonPollsPollIdRoute,
  CommonResultsRollNoRoute: CommonResultsRollNoRoute,
  CommonSchedulesSplatRoute: CommonSchedulesSplatRoute,
  CommonSyllabusCodeRoute: CommonSyllabusCodeRoute,
  CommonUUsernameRoute: CommonUUsernameRoute,
  CommonAnnouncementsIndexRoute: CommonAnnouncementsIndexRoute,
  CommonPollsIndexRoute: CommonPollsIndexRoute,
  CommonResourcesIndexRoute: CommonResourcesIndexRoute,
  CommonResultsIndexRoute: CommonResultsIndexRoute,
  CommonSchedulesIndexRoute: CommonSchedulesIndexRoute,
  CommonSyllabusIndexRoute: CommonSyllabusIndexRoute,
  CommonResourcesTypeSlugRoute: CommonResourcesTypeSlugRoute,
  CommonResourcesStoriesIdRoute: CommonResourcesStoriesIdRoute,
  CommonResourcesStoriesShareRoute: CommonResourcesStoriesShareRoute,
  CommonResourcesTypeIndexRoute: CommonResourcesTypeIndexRoute,
}

const CommonRouteWithChildren =
  CommonRoute._addFileChildren(CommonRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthVerifyMailRoute: typeof AuthVerifyMailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthVerifyMailRoute: AuthVerifyMailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DesignRouteChildren {
  DesignIndexRoute: typeof DesignIndexRoute
}

const DesignRouteChildren: DesignRouteChildren = {
  DesignIndexRoute: DesignIndexRoute,
}

const DesignRouteWithChildren =
  DesignRoute._addFileChildren(DesignRouteChildren)

interface ProgramsRouteChildren {
  ProgramsBuilderClubApplyNowRoute: typeof ProgramsBuilderClubApplyNowRoute
  ProgramsBuilderClubIndexRoute: typeof ProgramsBuilderClubIndexRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsBuilderClubApplyNowRoute: ProgramsBuilderClubApplyNowRoute,
  ProgramsBuilderClubIndexRoute: ProgramsBuilderClubIndexRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ModeratorRoute: ModeratorRouteWithChildren,
  CommonRoute: CommonRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DesignRoute: DesignRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ApiImageRoute: ApiImageRoute,
  ApiExperimentRoute: ApiExperimentRoute,
  ApiParsingRoute: ApiParsingRoute,
  ApiStatsRoute: ApiStatsRoute,
  OgSplatRoute: OgSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCommentsSplatRoute: ApiCommentsSplatRoute,
  ApiHostelAllotmentSlotRoute: ApiHostelAllotmentSlotRoute,
  ApiHostelRoomMembersRoute: ApiHostelRoomMembersRoute,
  ApiOutpassListRoute: ApiOutpassListRoute,
  ApiOutpassStatusRoute: ApiOutpassStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
