name: 🚀 Deployments Platform To Vercel



on:
  push:
    branches:
      - main
      - staging
      
  # workflow_dispatch:

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}-platform-deploy
  cancel-in-progress: true
  
jobs:
  # lint:
  #   uses: ./.github/workflows/lint-project.yml
  

  deploy-frontend-to-vercel:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🔍 Detect changed projects
        id: changed
        run: |
              git diff --quiet HEAD^ HEAD ./apps/platform || echo "platform_changed=true" >> $GITHUB_OUTPUT
      
      # - uses: pnpm/action-setup@v4

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v4
        if: steps.changed.outputs.platform_changed == 'true'
        with:
          node-version: 20.x
          cache: "npm"

      - name: 💾 Cache Vercel CLI
        uses: actions/cache@v4
        if: steps.changed.outputs.platform_changed == 'true'
        with:
          path: ~/.vercel
          key: ${{ runner.os }}-vercel-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-vercel-

      - name: 📦 Install Vercel CLI
        if: steps.changed.outputs.platform_changed == 'true'
        run: npm install -g vercel


      - name: 🎯 Deploy Platform to Staging
        if: github.ref == 'refs/heads/staging' && steps.changed.outputs.platform_changed == 'true'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} ./apps/platform
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PLATFORM_PROJECT_ID }}

      - name: 🚀 Deploy Platform to Production
        if: github.ref == 'refs/heads/main' && steps.changed.outputs.platform_changed == 'true'
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prod ./apps/platform
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PLATFORM_PROJECT_ID }}
